#version: "3"
services:
  ft-mongodb:
    image: mongo
    ports:
      - ${MONGO_PORT:-27017}:27017
    networks:
      - ft-network
    volumes:
      - ft-data-mongo:/data/db
    container_name: ft-mongo
    restart: always

  ft-redis:
    image: redis:alpine3.22
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    networks:
      - ft-network
    volumes:
      - ft-data-redis:/data
    container_name: ft-redis
    restart: always

  ft-front:
    build:
      dockerfile: Dockerfile
      context: ./admin/frontend
      args:
        - STS_SERVER=${STS_SERVER:-http://localhost:5000}
        - STS_ADMIN_SERVER=${STS_ADMIN_SERVER:-http://localhost:5001}
        - FRONT_PORT=${FRONT_PORT:-4200}
        - GO_PORT=${GO_PORT:-8085}
        - MS_MONGO_PORT=${MS_MONGO_PORT:-5050}
        - MONGO_PORT=${MONGO_PORT:-27027}
    image: ft/front
    container_name: ft-front
    restart: always
    ports:
      - ${FRONT_PORT}:80
    environment:
      - MS_MONGO_PORT=${MS_MONGO_PORT:-5050}
      - HOST=${HOST:-http://localhost}
      - STS_SERVER=${STS_SERVER:-http://localhost:5000}
      - STS_ADMIN_SERVER=${STS_ADMIN_SERVER:-http://localhost:5001}
      - FRONT_PORT=${FRONT_PORT:-4200}
      - GO_PORT=${GO_PORT:-8085}
      - MONGO_PORT=${MONGO_PORT:-27027}
    networks:
      - ft-network
    links:
      - ft-microservice
    depends_on:
      - ft-microservice

  ft-microservice:
    build:
      dockerfile: Dockerfile
      context: ./microserviceNodeJs
      args:
        - MONGO_PORT=${MONGO_PORT:-27017}
        - REDIS_SERVER=${REDIS_SERVER:-ft-redis}
        - REDIS_PORT=${REDIS_PORT:-6379}
        - MS_MONGO_PORT=${MS_MONGO_PORT:-5050}
    volumes:
      - ./microserviceNodeJs:/usr/src/app
    command: npm start
    image: ft/mongo/app
    container_name: ft-mongo-app
    restart: always
    ports:
      - ${MS_MONGO_PORT}:${MS_MONGO_PORT}
    environment:
      - MONGO_PORT=${MONGO_PORT:-27017}
      - REDIS_SERVER=${REDIS_SERVER:-ft-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - MS_MONGO_PORT=${MS_MONGO_PORT:-5050}
    networks:
      - ft-network
    depends_on:
      - "ft-mongodb"
      - "ft-redis"

  ft-ext-go:
    build:
      dockerfile: Dockerfile
      context: ./microserviceGo
    image: ft/ext/go
    container_name: ft-ext-go
    restart: always
    ports:
      - ${GO_PORT}:${GO_PORT:-8085}
    environment:
      - REDIS_SERVER=${REDIS_SERVER:-ft-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - PORT=${GO_PORT:-8085}
    networks:
      - ft-network
    depends_on:
      - "ft-redis"

networks:
  ft-network:
    driver: bridge
volumes:
  ft-data-redis:
  ft-data-mongo:
  ft-data-mongo-app:
