version: "3.9"

services:
  ft-sts-admin:
    build:
    
      dockerfile: Skoruba.IdentityServer4.Admin/Dockerfile
      context: ./IdentityServer4.Admin/src
    image: ft/sts/admin
    container_name: ft-sts-admin
    ports:
      - published: ${STS_ADMIN_PORT}
        target: 80
      - published: ${STS_ADMIN_HTTPS_PORT}
        target: 443
    environment:
      - ASPNETCORE_HTTPS_PORT=${STS_ADMIN_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:${STS_ADMIN_HTTPS_PORT};http://+:${STS_ADMIN_PORT}
      - Kestrel__Certificates__Default__Path=cert-aspnetcore.pfx
      - Kestrel__Certificates__Default__Password=ufo
      - AdminConfiguration:IdentityServerBaseUrl=${STS_SERVER}:${STS_PORT}
      - AdminConfiguration:IdentityAdminBaseUrl=${STS_ADMIN_SERVER}:${STS_ADMIN_PORT}
      - AdminConfiguration:IdentityAdminRedirectUri=${STS_ADMIN_SERVER}:${STS_ADMIN_PORT}/signin-oidc
    networks:
      - ft-network
    volumes:
      - ./IdentityServer4.Admin/src/db:/db
    links:
      - ft-sts
    depends_on:
      - ft-sts

  ft-sts:
    build:
      args:
        # - STS_ADMIN_PORT="${STS_ADMIN_PORT}"
        # - STS_ADMIN_SERVER=${STS_ADMIN_SERVER}
        # - STS_PORT="${STS_PORT}"
        # - STS_HTTPS_PORT="${STS_HTTPS_PORT}"
      dockerfile: Skoruba.IdentityServer4.STS.Identity/Dockerfile
      context: ./IdentityServer4.Admin/src
    image: ft/sts
    container_name: ft-sts
    ports:
      - published: ${STS_PORT}
        target: 80
      - published: ${STS_HTTPS_PORT}
        target: 443
    environment:
      - ASPNETCORE_HTTPS_PORT=${STS_HTTPS_PORT}
      - ASPNETCORE_URLS=https://+:${STS_HTTPS_PORT};http://+:${STS_PORT}
      - Kestrel__Certificates__Default__Path=cert-aspnetcore.pfx
      - Kestrel__Certificates__Default__Password=ufo
      - AdminConfiguration:IdentityAdminBaseUrl=${STS_ADMIN_SERVER}:${STS_ADMIN_PORT}
    networks:
      - ft-network
    volumes:
      - ./IdentityServer4.Admin/src/db:/db

networks:
  ft-network:
    driver: bridge
volumes:
  ft-sts-admin-db:
  ft-sts-db:
